### PR TITLE
poolboy connection

### PR DESCRIPTION
**Pull request by peillis**
This is another approach, but how do you suggest to use the pool on the Memcache module?

### CODE REVIEW

**Comment by ananthakumaran** [comment]
Does this actually provide much value? Can you add couple of examples/tests?

We are adding a dependency, but not providing any better interface. I am assuming all the calls still need to wrapped with `:poolboy.transaction`.

**Comment by peillis** [comment]
The thing is we should be able to have multiple pools (to connect to multiple servers in a cluster), is the same as with the Memcache module, it's an agent with a connection. Pool should be something similar and use it like:
```
{ :ok, pid } = Memcache.Connection.Pool.start_link()
{ :ok } = Memcache.Connection.Pool.set(pid, "hello", "world")
{ :ok, "world" } = Memcache.Connection.Pool.get(pid, "hello")
```
It makes no sense to provide a better interface on the pool. I think the better interface should be on the Application module, which is configured with the Mix.config

**Comment by peillis** [comment]
any thoughts?

**Comment by ananthakumaran** [comment]
I like the direction this is going. I will take a closer look at it over the weekend.

is there any way to reuse the memcache/api.ex in memcache.ex.

one thought is, may be memcache/api.ex can be a behaviour, so memcache & memcache pool module would implement start_link, init, stop, execute etc

**Comment by peillis** [comment]
Yes, memcache/api.ex must definitively be a behaviour.
About memcache.ex I think at the end is gonna be completely different, so I don't want to touch that yet.

**Comment by peillis** [comment]
Any plan on updating the library?

**Pull request closed without merging**
