### PR TITLE
Support `:default` opt in `cas/4`

### PR DESCRIPTION
**Pull request by jzimbel-mbta**
Proposed change for #30.

I updated tests ~~but am not able to run them locally, sorry!~~

Thanks in advance for reviewing.

### CODE REVIEW

**Comment by ananthakumaran** [comment]
This a nice feature to add and thanks for working on it. The implementation needs to be revised. Start with the following test

```elixir
  test "cas_default" do
    assert {:ok, pid} = Memcache.start_link(port: 21_211)
    assert {:ok} = Memcache.flush(pid)

    1..300
    |> Task.async_stream(
      fn _i ->
        Memcache.cas(pid, "counter", &Integer.to_string(String.to_integer(&1) + 1), default: "1")
      end,
      max_concurrency: 5
    )
    |> Stream.run()

    assert {:ok, "300"} == Memcache.get(pid, "counter")
  end
```

Try to understand why it fails and what can be done to fix it.

<details>
  <summary>hint</summary>
   I would suggest looking at add operation and if it fails, then that implies somebody else has added the key in the meantime, we have to go back and do the normal cas.
</details>


One more suggestion, we could change the default value to a value or function with no args like Logger.info for example, this would make it lazy and will not be executed all the time. Think about the case where we cache the total friends count, adding a new friend could just increment the existing value, but calculating default would require going to DB, etc, so it would be better if the operation is done only when it's needed.

**Comment by jzimbel-mbta** [comment]
Good idea on allowing lazy computation of the default value.

What do you think about following the precedent of Elixir's `Map` module and defining a separate `cas_lazy(server, key, updater_fun, default_fun, opts)` function for that use case? E.g. [`Map.get_lazy/3`](https://github.com/elixir-lang/elixir/blob/v1.14.1/lib/elixir/lib/map.ex#L561) and other `*_lazy` functions in that module.

**Comment by jzimbel-mbta** [comment]
Thank you for catching that condition and sharing a test case for it. :)

The `:default` option should now work as intended, but I would like to improve the code's readability, possibly with helper functions, since I've made the function's cyclomatic complexity very high.

I will also try to add support for the 0-arity-function default value.

**Comment by jzimbel-mbta** [comment]
Ok, lazy-evaluated `:default` opt is now supported. I've also updated the documentation and added an additional set of tests for the lazy default feature.

This is ready for another review now; thanks again for being open to this change. :)

**Pull request merged**
